# Generated by Django 4.1.7 on 2023-02-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="phone number"
            ),
        ),
    ]
